language: perl
install:
  - cpanm -n -q --skip-satisfied --installdeps .
script: perl Makefile.PL && make test
perl:
  - "5.21"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
